#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using TH.Item;
using TH.Resource;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

public static class OutfitAutoGeneratedAssetMaintenanceTool
{
    private const string OutfitDataAddressKey = "outfit.data.folder";
    private const string OutputIconsAddressKey = "outfit.icons_output.folder";
    private const string ArmorOutputDataAddressKey = "armor.output_data.folder";

    private const string MaleTemplateAddressKey = "outfit.template.male";
    private const string FemaleTemplateAddressKey = "outfit.template.female";

    private static readonly string[] TemplateAddressKeys =
    {
        MaleTemplateAddressKey,
        FemaleTemplateAddressKey
    };

    [MenuItem("Tools/Outfit/Report Invalid Auto-Generated Outfit Assets")]
    private static void ReportInvalidAssets()
    {
        var scan = ScanInvalidAssets();
        LogScanResult(scan, "REPORT");
    }

    [MenuItem("Tools/Outfit/Cleanup Invalid Auto-Generated Outfit Assets")]
    private static void CleanupInvalidAssets()
    {
        var scan = ScanInvalidAssets();
        LogScanResult(scan, "BEFORE CLEANUP");

        if (!scan.HasAnyInvalid)
        {
            Debug.Log("[OutfitAutoGeneratedAssetMaintenanceTool] Nothing to clean.");
            return;
        }

        var confirm = EditorUtility.DisplayDialog(
            "Cleanup Invalid Outfit Assets",
            $"Invalid template tags: {scan.InvalidTemplateTags.Count}\n" +
            $"Invalid OutfitKeySO: {scan.InvalidOutfitKeyPaths.Count}\n" +
            $"Invalid icons: {scan.InvalidIconPaths.Count}\n" +
            $"Invalid ArmorTypeSO: {scan.InvalidArmorPaths.Count}\n\n" +
            "Proceed with cleanup?",
            "Cleanup",
            "Cancel");

        if (!confirm)
        {
            Debug.Log("[OutfitAutoGeneratedAssetMaintenanceTool] Cleanup canceled.");
            return;
        }

        int removedTags = RemoveInvalidTemplateTags();
        int deletedAssets = 0;
        int failedDeletes = 0;

        DeleteAssets(scan.InvalidOutfitKeyPaths, ref deletedAssets, ref failedDeletes);
        DeleteAssets(scan.InvalidIconPaths, ref deletedAssets, ref failedDeletes);
        DeleteAssets(scan.InvalidArmorPaths, ref deletedAssets, ref failedDeletes);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        var remaining = ScanInvalidAssets();
        Debug.Log(
            $"[OutfitAutoGeneratedAssetMaintenanceTool] Cleanup finished. " +
            $"RemovedTags={removedTags}, DeletedAssets={deletedAssets}, FailedDeletes={failedDeletes}, RemainingInvalid={remaining.TotalInvalidCount}");

        if (remaining.HasAnyInvalid)
            LogScanResult(remaining, "AFTER CLEANUP");
    }

    private static ScanResult ScanInvalidAssets()
    {
        var result = new ScanResult();

        var outfitDataPath = ResolvePathByAddressKey(OutfitDataAddressKey);
        var iconOutputPath = ResolvePathByAddressKey(OutputIconsAddressKey);
        var armorOutputPath = ResolvePathByAddressKey(ArmorOutputDataAddressKey);

        if (!string.IsNullOrEmpty(outfitDataPath))
            CollectInvalidOutfitKeys(outfitDataPath, result);

        if (!string.IsNullOrEmpty(iconOutputPath))
            CollectInvalidIcons(iconOutputPath, result);

        if (!string.IsNullOrEmpty(armorOutputPath))
            CollectInvalidArmors(armorOutputPath, result);

        CollectInvalidTemplateTags(result);
        return result;
    }

    private static void CollectInvalidOutfitKeys(string outfitDataPath, ScanResult result)
    {
        var guids = AssetDatabase.FindAssets("t:OutfitKeySO", new[] { outfitDataPath });
        var idCount = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

        for (int i = 0; i < guids.Length; i++)
        {
            var path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var key = AssetDatabase.LoadAssetAtPath<OutfitKeySO>(path);
            if (key == null)
                continue;

            if (!string.IsNullOrWhiteSpace(key.id))
            {
                idCount.TryGetValue(key.id, out var count);
                idCount[key.id] = count + 1;
            }

            if (!OutfitAutoGenerationRules.IsAutoGeneratableOutfitKey(key))
                result.InvalidOutfitKeyPaths.Add(path);
        }

        foreach (var pair in idCount)
        {
            if (pair.Value > 1)
                result.DuplicateOutfitKeyIds.Add($"{pair.Key} (x{pair.Value})");
        }
    }

    private static void CollectInvalidIcons(string iconOutputPath, ScanResult result)
    {
        var guids = AssetDatabase.FindAssets("t:Texture2D", new[] { iconOutputPath });
        for (int i = 0; i < guids.Length; i++)
        {
            var path = AssetDatabase.GUIDToAssetPath(guids[i]);
            if (!path.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
                continue;

            var iconId = Path.GetFileNameWithoutExtension(path);
            if (!OutfitAutoGenerationRules.IsAllowedOutfitIdentifier(iconId))
                result.InvalidIconPaths.Add(path);
        }
    }

    private static void CollectInvalidArmors(string armorOutputPath, ScanResult result)
    {
        var guids = AssetDatabase.FindAssets("t:ArmorTypeSO", new[] { armorOutputPath });
        for (int i = 0; i < guids.Length; i++)
        {
            var path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var armor = AssetDatabase.LoadAssetAtPath<ArmorTypeSO>(path);
            if (armor == null)
                continue;

            var fileName = Path.GetFileNameWithoutExtension(path);
            var fromName = fileName.StartsWith("Armor_", StringComparison.OrdinalIgnoreCase)
                ? fileName.Substring("Armor_".Length)
                : fileName;

            bool invalidByName = !OutfitAutoGenerationRules.IsAllowedOutfitIdentifier(fromName);
            bool invalidByKey = armor.OutfitKey != null && !OutfitAutoGenerationRules.IsAutoGeneratableOutfitKey(armor.OutfitKey);

            if (invalidByName || invalidByKey)
                result.InvalidArmorPaths.Add(path);
        }
    }

    private static void CollectInvalidTemplateTags(ScanResult result)
    {
        var templatePaths = ResolveTemplatePrefabPaths();
        for (int i = 0; i < templatePaths.Count; i++)
        {
            var templatePath = templatePaths[i];
            var root = PrefabUtility.LoadPrefabContents(templatePath);

            try
            {
                var tags = root.GetComponentsInChildren<OutfitPartKeyTag>(true);
                for (int t = 0; t < tags.Length; t++)
                {
                    var tag = tags[t];
                    if (tag == null)
                        continue;

                    if (!OutfitAutoGenerationRules.IsExcludedOutfitIdentifier(tag.gameObject.name))
                        continue;

                    result.InvalidTemplateTags.Add(new TemplateTagInfo
                    {
                        TemplatePath = templatePath,
                        HierarchyPath = GetHierarchyPath(tag.transform, root.transform),
                        PartName = tag.gameObject.name
                    });
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }
    }

    private static int RemoveInvalidTemplateTags()
    {
        int removed = 0;
        var templatePaths = ResolveTemplatePrefabPaths();

        for (int i = 0; i < templatePaths.Count; i++)
        {
            var templatePath = templatePaths[i];
            var root = PrefabUtility.LoadPrefabContents(templatePath);
            bool changed = false;

            try
            {
                var tags = root.GetComponentsInChildren<OutfitPartKeyTag>(true);
                for (int t = 0; t < tags.Length; t++)
                {
                    var tag = tags[t];
                    if (tag == null)
                        continue;

                    if (!OutfitAutoGenerationRules.IsExcludedOutfitIdentifier(tag.gameObject.name))
                        continue;

                    UnityEngine.Object.DestroyImmediate(tag, true);
                    removed++;
                    changed = true;
                }

                if (changed)
                    PrefabUtility.SaveAsPrefabAsset(root, templatePath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        return removed;
    }

    private static void DeleteAssets(List<string> paths, ref int deletedAssets, ref int failedDeletes)
    {
        if (paths == null)
            return;

        var uniquePaths = new HashSet<string>(paths, StringComparer.OrdinalIgnoreCase);
        foreach (var path in uniquePaths)
        {
            RemoveAddressableEntry(path);

            if (AssetDatabase.DeleteAsset(path))
                deletedAssets++;
            else
                failedDeletes++;
        }
    }

    private static void RemoveAddressableEntry(string assetPath)
    {
        if (string.IsNullOrWhiteSpace(assetPath))
            return;

        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
            return;

        var guid = AssetDatabase.AssetPathToGUID(assetPath);
        if (string.IsNullOrEmpty(guid))
            return;

        var entry = settings.FindAssetEntry(guid);
        if (entry != null)
            settings.RemoveAssetEntry(guid, false);
    }

    private static List<string> ResolveTemplatePrefabPaths()
    {
        var result = new List<string>();

        for (int i = 0; i < TemplateAddressKeys.Length; i++)
        {
            var path = ResolvePathByAddressKey(TemplateAddressKeys[i]);
            if (string.IsNullOrEmpty(path))
                continue;

            if (!result.Contains(path))
                result.Add(path);
        }

        return result;
    }

    private static string ResolvePathByAddressKey(string addressKey)
    {
        return EditorAddressablePathResolver.ResolvePathByMapIdOrAddressKey(
            addressKey,
            nameof(OutfitAutoGeneratedAssetMaintenanceTool));
    }

    private static string GetHierarchyPath(Transform current, Transform root)
    {
        if (current == null || root == null)
            return string.Empty;

        if (current == root)
            return root.name;

        var stack = new Stack<string>();
        var walker = current;
        while (walker != null)
        {
            stack.Push(walker.name);
            if (walker == root)
                break;

            walker = walker.parent;
        }

        return string.Join("/", stack);
    }

    private static void LogScanResult(ScanResult scan, string title)
    {
        Debug.Log(
            $"[OutfitAutoGeneratedAssetMaintenanceTool][{title}] " +
            $"InvalidTemplateTags={scan.InvalidTemplateTags.Count}, " +
            $"InvalidOutfitKeys={scan.InvalidOutfitKeyPaths.Count}, " +
            $"InvalidIcons={scan.InvalidIconPaths.Count}, " +
            $"InvalidArmors={scan.InvalidArmorPaths.Count}, " +
            $"DuplicateOutfitKeyIds={scan.DuplicateOutfitKeyIds.Count}");

        for (int i = 0; i < scan.InvalidTemplateTags.Count; i++)
        {
            var tag = scan.InvalidTemplateTags[i];
            Debug.LogWarning($"[OutfitAutoGeneratedAssetMaintenanceTool][{title}] InvalidTemplateTag: template={tag.TemplatePath}, object={tag.HierarchyPath}, partName={tag.PartName}");
        }

        LogPathList(scan.InvalidOutfitKeyPaths, "InvalidOutfitKey", title);
        LogPathList(scan.InvalidIconPaths, "InvalidIcon", title);
        LogPathList(scan.InvalidArmorPaths, "InvalidArmor", title);

        for (int i = 0; i < scan.DuplicateOutfitKeyIds.Count; i++)
        {
            Debug.LogWarning($"[OutfitAutoGeneratedAssetMaintenanceTool][{title}] DuplicateOutfitKeyId: {scan.DuplicateOutfitKeyIds[i]}");
        }
    }

    private static void LogPathList(List<string> paths, string label, string title)
    {
        for (int i = 0; i < paths.Count; i++)
        {
            Debug.LogWarning($"[OutfitAutoGeneratedAssetMaintenanceTool][{title}] {label}: {paths[i]}");
        }
    }

    private sealed class ScanResult
    {
        public readonly List<TemplateTagInfo> InvalidTemplateTags = new();
        public readonly List<string> InvalidOutfitKeyPaths = new();
        public readonly List<string> InvalidIconPaths = new();
        public readonly List<string> InvalidArmorPaths = new();
        public readonly List<string> DuplicateOutfitKeyIds = new();

        public int TotalInvalidCount => InvalidTemplateTags.Count + InvalidOutfitKeyPaths.Count + InvalidIconPaths.Count + InvalidArmorPaths.Count;
        public bool HasAnyInvalid => TotalInvalidCount > 0;
    }

    private struct TemplateTagInfo
    {
        public string TemplatePath;
        public string HierarchyPath;
        public string PartName;
    }
}
#endif
