using System;
using System.IO;
using TH.Attribute.Stat;
using TH.Resource;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace TH.Combat.Drop.Editor
{
    public static class EnemyDropTableBatchSetupEditor
    {
        private const string MenuPath = "Tools/Combat/Drop/Setup NPC Enemy Drop Tables";
        private const string OutputFolder = "Assets/Game/Combat/DropTables/AutoGenerated";

        [MenuItem(MenuPath)]
        private static void SetupAll()
        {
            EnsureFolder(OutputFolder);

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            var npcGuids = AssetDatabase.FindAssets("t:NpcTypeSO", new[] { "Assets" });

            var scanned = 0;
            var enemyCount = 0;
            var createdTables = 0;
            var reusedTables = 0;
            var assignedReferences = 0;
            var skippedNonEnemy = 0;
            var failed = 0;

            foreach (var npcGuid in npcGuids)
            {
                var npcPath = AssetDatabase.GUIDToAssetPath(npcGuid);
                if (string.IsNullOrWhiteSpace(npcPath))
                    continue;

                var npc = AssetDatabase.LoadAssetAtPath<NpcTypeSO>(npcPath);
                if (npc == null)
                    continue;

                scanned++;
                if (!IsEnemyType(npc.characterType))
                {
                    skippedNonEnemy++;
                    continue;
                }

                enemyCount++;

                var table = ResolveReferencedDropTable(npc);
                if (table == null)
                {
                    table = ResolveOrCreateDropTableAsset(npcPath, out var created);
                    if (table == null)
                    {
                        failed++;
                        continue;
                    }

                    if (created)
                        createdTables++;
                    else
                        reusedTables++;
                }
                else
                {
                    reusedTables++;
                }

                var tablePath = AssetDatabase.GetAssetPath(table);
                EnsureAddressableRegistration(settings, tablePath);

                if (!AssignDropTableReference(npc, tablePath))
                {
                    failed++;
                    continue;
                }

                assignedReferences++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[{nameof(EnemyDropTableBatchSetupEditor)}] scanned={scanned}, enemy={enemyCount}, createdTables={createdTables}, reusedTables={reusedTables}, assignedReferences={assignedReferences}, skippedNonEnemy={skippedNonEnemy}, failed={failed}");
        }

        private static bool IsEnemyType(CharacterType characterType)
        {
            return characterType.ToString().StartsWith("Enemy", StringComparison.Ordinal);
        }

        private static EnemyDropTableSO ResolveReferencedDropTable(NpcTypeSO npc)
        {
            var npcSo = new SerializedObject(npc);
            var referenceProp = npcSo.FindProperty("enemyDropTableReference");
            var guidProp = referenceProp?.FindPropertyRelative("m_AssetGUID");

            if (guidProp == null || string.IsNullOrWhiteSpace(guidProp.stringValue))
                return null;

            var assetPath = AssetDatabase.GUIDToAssetPath(guidProp.stringValue);
            if (string.IsNullOrWhiteSpace(assetPath))
                return null;

            return AssetDatabase.LoadAssetAtPath<EnemyDropTableSO>(assetPath);
        }

        private static EnemyDropTableSO ResolveOrCreateDropTableAsset(string npcPath, out bool created)
        {
            created = false;
            var npcName = Path.GetFileNameWithoutExtension(npcPath);
            var candidatePath = $"{OutputFolder}/{npcName}_DropTable.asset";

            var existing = AssetDatabase.LoadAssetAtPath<EnemyDropTableSO>(candidatePath);
            if (existing != null)
                return existing;

            var table = ScriptableObject.CreateInstance<EnemyDropTableSO>();
            if (table == null)
                return null;

            var createdPath = AssetDatabase.GenerateUniqueAssetPath(candidatePath);
            AssetDatabase.CreateAsset(table, createdPath);
            created = true;
            return table;
        }

        private static bool AssignDropTableReference(NpcTypeSO npc, string tablePath)
        {
            if (npc == null || string.IsNullOrWhiteSpace(tablePath))
                return false;

            var tableGuid = AssetDatabase.AssetPathToGUID(tablePath);
            if (string.IsNullOrWhiteSpace(tableGuid))
                return false;

            var npcSo = new SerializedObject(npc);
            var referenceProp = npcSo.FindProperty("enemyDropTableReference");
            if (referenceProp == null)
                return false;

            var guidProp = referenceProp.FindPropertyRelative("m_AssetGUID");
            var subObjectNameProp = referenceProp.FindPropertyRelative("m_SubObjectName");
            var subObjectTypeProp = referenceProp.FindPropertyRelative("m_SubObjectType");

            if (guidProp == null || subObjectNameProp == null || subObjectTypeProp == null)
                return false;

            guidProp.stringValue = tableGuid;
            subObjectNameProp.stringValue = string.Empty;
            subObjectTypeProp.stringValue = string.Empty;

            npcSo.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(npc);
            return true;
        }

        private static void EnsureAddressableRegistration(AddressableAssetSettings settings, string assetPath)
        {
            if (settings == null || string.IsNullOrWhiteSpace(assetPath))
                return;

            var guid = AssetDatabase.AssetPathToGUID(assetPath);
            if (string.IsNullOrWhiteSpace(guid))
                return;

            var entry = settings.FindAssetEntry(guid);
            if (entry == null)
                entry = settings.CreateOrMoveEntry(guid, settings.DefaultGroup, false, true);

            if (entry == null)
                return;

            entry.address = assetPath;
            EditorUtility.SetDirty(settings);
        }

        private static void EnsureFolder(string folderPath)
        {
            if (AssetDatabase.IsValidFolder(folderPath))
                return;

            var normalized = folderPath.Replace("\\", "/");
            var parts = normalized.Split('/');
            if (parts.Length == 0)
                return;

            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = parts[i];
                var combined = $"{current}/{next}";
                if (!AssetDatabase.IsValidFolder(combined))
                    AssetDatabase.CreateFolder(current, next);

                current = combined;
            }
        }
    }
}
